# Generated by Django 4.0.1 on 2022-01-12 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'wykładowca', 'verbose_name_plural': 'wykładowcy'},
        ),
    ]
