# Generated by Django 4.0.1 on 2022-01-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='academic_degree',
            new_name='academic_deegree',
        ),
    ]
