# Generated by Django 4.0.1 on 2022-01-12 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_academic_degree_profile_academic_deegree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='academic_deegree',
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_degree',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Stopień akademicki'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Numer telefonu'),
        ),
    ]
