# Generated by Django 4.0.1 on 2022-01-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_academic_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='academic_degree',
            field=models.CharField(choices=[('Mgr', 'Mgr'), ('Dr', 'Dr'), ('Dr habilitowany', 'Dr habilitowany'), ('Prof. nadzwyczajny', 'Prof. nadzwyczajny'), ('Prof. zwyczajny', 'Prof. zwyczajny')], default='magister', max_length=30, verbose_name='Stopień akademicki'),
        ),
    ]
