# Generated by Django 4.0.1 on 2022-01-21 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'Newsy'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='reporter',
            new_name='author',
        ),
    ]
