# Generated by Django 4.0.1 on 2022-01-11 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='liczebność grupy')),
                ('group_number', models.IntegerField(verbose_name='numer grupy')),
            ],
            options={
                'verbose_name': 'grupa',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(max_length=100, verbose_name='nazwa zajęć')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, verbose_name='nazwa sali')),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(max_length=255, verbose_name='opis sali')),
            ],
            options={
                'verbose_name': 'sala',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=100, verbose_name='nazwa planu')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plany',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(max_length=100, verbose_name='kierunek')),
            ],
            options={
                'verbose_name': 'rok',
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.group')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.lecture')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
            ],
            options={
                'verbose_name': 'pozycja planu',
            },
        ),
        migrations.CreateModel(
            name='RoomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.room')),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduleitem')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduleitem')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.weekday')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.year'),
        ),
    ]
