# Generated by Django 4.0.1 on 2022-01-12 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'grupa', 'verbose_name_plural': 'grupy'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'sala', 'verbose_name_plural': 'sale'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'verbose_name': 'rok', 'verbose_name_plural': 'kierunki'},
        ),
        migrations.AlterField(
            model_name='lectureritem',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
