# Generated by Django 4.0.1 on 2022-01-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_lectureravailability_from_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='type_of_semester',
            field=models.CharField(choices=[('letni', 'letni'), ('zimowy', 'zimowy')], default='letni', max_length=100),
        ),
        migrations.AddField(
            model_name='year',
            name='type_of_studies',
            field=models.CharField(choices=[('stacjonarne', 'stacjonarne'), ('niestacjonarne', 'niestacjonarne')], default='stacjonarne', max_length=100),
        ),
        migrations.AddField(
            model_name='year',
            name='year_period',
            field=models.CharField(default='2022', max_length=9, verbose_name='rok akademicki (yyyy/yyyy)'),
        ),
    ]
