# Generated by Django 4.0.1 on 2022-01-13 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_year_type_of_semester_year_type_of_studies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='speciality',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Specjalność'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='year',
            name='type_of_semester',
            field=models.CharField(choices=[('letni', 'letni'), ('zimowy', 'zimowy')], default='letni', max_length=100, verbose_name='Rodzaj semestru'),
        ),
        migrations.AlterField(
            model_name='year',
            name='type_of_studies',
            field=models.CharField(choices=[('stacjonarne', 'stacjonarne'), ('niestacjonarne', 'niestacjonarne')], default='stacjonarne', max_length=100, verbose_name='Tok studiów'),
        ),
        migrations.AlterField(
            model_name='year',
            name='year_period',
            field=models.CharField(default='2021/2022', max_length=9, verbose_name='Rok akademicki (yyyy/yyyy)'),
        ),
    ]
