# Generated by Django 4.0.1 on 2022-01-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_year_speciality_alter_year_type_of_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='break_time',
            field=models.IntegerField(default=15, verbose_name='długość przerwy (w minutach)'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lecture_unit',
            field=models.IntegerField(default=45, verbose_name='długość jednostki godzinowej (w minutach)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(verbose_name='pojemnosc'),
        ),
        migrations.AlterField(
            model_name='year',
            name='type_of_semester',
            field=models.CharField(default='letni', max_length=100, verbose_name='Rodzaj semestru'),
        ),
        migrations.AlterField(
            model_name='year',
            name='type_of_studies',
            field=models.CharField(default='stacjonarne', max_length=100, verbose_name='Tok studiów'),
        ),
    ]
