# Generated by Django 4.0.1 on 2022-01-15 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_schedule_break_time_schedule_lecture_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.year', verbose_name='Powiązany kierunek'),
        ),
    ]
