# Generated by Django 4.0.1 on 2022-01-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_scheduleitem_lecture_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek'), (5, 'Sobota'), (6, 'Niedziela')], null=True),
        ),
    ]
