# Generated by Django 4.0.1 on 2022-01-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_alter_scheduleitem_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type_of_lecture',
            field=models.IntegerField(choices=[(0, 'Laboratorium'), (1, 'Ćwiczenia'), (2, 'Wykład')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='type_of_lecture',
            field=models.IntegerField(choices=[(0, 'Laboratorium'), (1, 'Ćwiczenia'), (2, 'Wykład')], default=1),
            preserve_default=False,
        ),
    ]
