# Generated by Django 4.0.1 on 2022-01-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_alter_roomitem_schedule_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='lecture_units',
            field=models.IntegerField(default=2),
        ),
    ]
